#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "laravel" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'laravel' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER laravel
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

mkdir -p /var/log/supervisor

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    # Iniciar supervisord en foreground
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
